# Generated by Django 3.1.3 on 2020-12-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
