# Generated by Django 3.1.3 on 2020-12-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_log', '0002_auto_20201202_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TextField(),
        ),
    ]
