# Generated by Django 3.1.4 on 2020-12-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_log', '0004_meal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='quantity',
            field=models.TextField(default='Not entered'),
            preserve_default=False,
        ),
    ]
