# Generated by Django 3.1.3 on 2020-12-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_nutrient', models.TextField()),
                ('product_amount', models.TextField()),
                ('product_unit', models.TextField()),
            ],
        ),
    ]
